# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models


def moveUserIdToObjId(apps, schema_editor):
    SentDrip = apps.get_model('drip', 'SentDrip')
    for sd in SentDrip.objects.all():
        sd.objId = sd.user.id
        sd.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0002_auto_20190821_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdrip',
            name='objId',
            field=models.IntegerField(default=0, verbose_name='Object ID'),
            preserve_default=False,
        ),
        migrations.RunPython(moveUserIdToObjId),
        migrations.RemoveField(
            model_name='sentdrip',
            name='user',
        ),
    ]
